### ISSUE TITLE
Patch Coordinates?

### ISSUE THREAD

**Issue by TaranRai** [jgamper/compay-syntax#12]
Hi,

This is a brill repo!

I was wondering whether it is possible to retrieve the coordinates of the patches. For example, are the patches randomly retrieved?

Taran

**Comment by jgamper** [comment]
Hi @TaranRai, yes it is possible to retrieve the coordinates of the patches. They are sampled randomly in the current version. See readme for an example. Once the sampling has been done, the coordinates will be in a dataframe object on `slide.tile_frame.to_csv(..)` [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_csv.html)
